version: '3.8'

services:
  dte-fdm-api:
    build:
      context: ./DTE_FDM_service
      dockerfile: Dockerfile
    container_name: dte_fdm_server
    ports:
      - "8001:8001"
    volumes:
      - .:/workspace/fakeshield
    environment:
      - PYTHONPATH=/workspace/fakeshield:/workspace/fakeshield/DTE_FDM
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    command: uvicorn DTE_FDM_service.main:app --host 0.0.0.0 --port 8001 --reload

  mflm-api:
    build:
      context: ./MFLM_service
      dockerfile: Dockerfile
    container_name: mflm_server
    ports:
      - "8002:8002"
    volumes:
      - .:/workspace/fakeshield
    environment:
      - PYTHONPATH=/workspace/fakeshield:/workspace/fakeshield/MFLM
    ulimits:
      memlock: -1
      stack: 67108864
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    command: uvicorn MFLM_service.main:app --host 0.0.0.0 --port 8002 --reload

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway_service
    ports:
      - "8000:8000"
    volumes:
      - ./gateway-service:/workspace/gateway-service
      - ./playground:/workspace/playground
    ipc: host
    command: uvicorn gateway-service.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      mflm-api:
        condition: service_started
      dte-fdm-api:
        condition: service_started
