version: '3.8'

services:
  dte-fdm-api:
    build:
      context: ./DTE-FDM-service
      dockerfile: Dockerfile
    container_name: dte_fdm_server
    ports:
      - "8001:8001"
    volumes:
      - .:/workspace/fakeshield
    environment:
      - PYTHONPATH=/workspace/fakeshield:/workspace/fakeshield/DTE_FDM
      - DTE_FDM_LOAD_8BIT=${DTE_FDM_LOAD_8BIT}
      - DTE_FDM_LOAD_4BIT=${DTE_FDM_LOAD_4BIT}
      - LOAD_MODEL_ON_STARTUP=${LOAD_DTE_FDM_ON_STARTUP}
      - DEBUG_FLAG=${DEBUG_FLAG}
      - MODEL_PATH=${MODEL_PATH}
      - DTG_PATH=${DTG_PATH}
      - TIMEOUT_DTE_FDM=${TIMEOUT_DTE_FDM}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    command: uvicorn DTE-FDM-service.main:app --host 0.0.0.0 --port 8001 --reload

  mflm-api:
    build:
      context: ./MFLM-service
      dockerfile: Dockerfile
    container_name: mflm_server
    ports:
      - "8002:8002"
    volumes:
      - .:/workspace/fakeshield
    environment:
      - PYTHONPATH=/workspace/fakeshield:/workspace/fakeshield/MFLM
      - LOAD_MODEL_ON_STARTUP=${LOAD_MFLM_ON_STARTUP}
      - DEBUG_FLAG=${DEBUG_FLAG}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    command: uvicorn MFLM-service.main:app --host 0.0.0.0 --port 8002 --reload

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway_service
    ports:
      - "8000:8000"
    volumes:
      - ./gateway-service:/workspace/gateway-service
      - ./playground:/workspace/playground
    environment:
      - MFLM_SERVICE=${MFLM_SERVICE}
      - DTE_FDM_SERVICE=${DTE_FDM_SERVICE}
      - DEBUG_FLAG=${DEBUG_FLAG}
    ipc: host
    command: uvicorn gateway-service.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      mflm-api:
        condition: service_started
      dte-fdm-api:
        condition: service_started
